# Generated by Django 5.2.6 on 2026-02-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselPhoto',
        ),
    ]
