# Generated by Django 5.2.6 on 2025-09-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100, verbose_name='Название Филлиала')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона филлиала')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email филлиала')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес филлиала')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Контактный номер в Whastapp \n wa.me/+phone_number')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Страница филлиала в Instagram \n https://www.instagram.com/Nickname')),
                ('country', models.CharField(choices=[('am', 'America'), ('fr', 'Français'), ('de', 'Deutsch')], default='am', max_length=15, verbose_name='Страна филлиала')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch')], default='en', max_length=5, verbose_name='Основной язык филлиала')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='Автор отзыва')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата добавления отзыва')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch')], max_length=5, verbose_name='Выбор языка на отзыве')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название мебели | Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание мебели')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Фотография мебели')),
                ('date', models.DateField(blank=True, verbose_name='Дата изготовления')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch')], max_length=5, verbose_name='Выбор языка на работе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
