# Generated by Django 6.0.2 on 2026-02-03 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carousel photo',
                'verbose_name_plural': 'Carousel photos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание категории (не обязательно)')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('consultation_type', models.CharField(choices=[('design', 'Дизайн-проект'), ('custom', 'На заказ'), ('repair', 'Ремонт/Реставрация'), ('general', 'Общая консультация')], default='general', max_length=20, verbose_name='Тип консультации')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('preferred_time', models.CharField(blank=True, max_length=50, verbose_name='Предпочтительное время')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка на консультацию',
                'verbose_name_plural': 'Заявки на консультацию',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100, verbose_name='Название Филлиала')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона филлиала')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email филлиала')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес филлиала')),
                ('start_time', models.TimeField(blank=True, help_text='Пример: 9:00', null=True, verbose_name='Открытие филлиала')),
                ('end_time', models.TimeField(blank=True, help_text='Пример: 24:00', null=True, verbose_name='Закрытие филлиала')),
                ('whatsapp', models.URLField(blank=True, default='wa.me/+', help_text='wa.me/+phone_number', null=True, verbose_name='Контактный номер в Whastapp')),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/', help_text='https://www.instagram.com/Nickname"', null=True, verbose_name='Страница филлиала в Instagram')),
                ('country', models.CharField(choices=[('fr', 'Français'), ('at', 'Austria')], default='am', max_length=15, verbose_name='Страна филлиала')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('at', 'Deutsch')], default='en', max_length=5, verbose_name='Основной язык филлиала')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='Автор отзыва')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], default=5, verbose_name='Рейтинг')),
                ('project_name', models.CharField(blank=True, default='Мебель на заказ', max_length=200, verbose_name='Название проекта')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Проверенный клиент')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Количество полезных голосов')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата добавления отзыва')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('at', 'Deutsch')], max_length=5, verbose_name='Выбор языка на отзыве')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество довольных клиентов')),
                ('projects_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Колисество выполненных работ')),
                ('years_experience', models.IntegerField(blank=True, default=0, null=True, verbose_name='Опыт работы')),
                ('delivery_weeks', models.IntegerField(blank=True, default=0, help_text='Указывайте количество недель', null=True, verbose_name='время доставки')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мебели')),
                ('description', models.TextField(blank=True, verbose_name='Описание мебели')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Фотография мебели')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('usd', 'USD $'), ('eur', 'EUR €')], default='usd', max_length=5, verbose_name='Валюта')),
                ('country', models.CharField(choices=[('fr', 'France'), ('at', 'Austria')], default='us', max_length=5, verbose_name='Страна работы')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата изготовления')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('at', 'Deutsch')], max_length=5, verbose_name='Выбор языка на работе')),
                ('work_type', models.CharField(choices=[('custom', 'На заказ'), ('template', 'По шаблону'), ('restoration', 'Реставрация'), ('assembly', 'Сборка'), ('design', 'Дизайн-проект')], default='custom', max_length=20, verbose_name='Тип работы')),
                ('status', models.CharField(choices=[('in_progress', 'В производстве'), ('completed', 'Готово'), ('delivered', 'Доставлено')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Материал')),
                ('our_work', models.BooleanField(blank=True, default=False, null=True, verbose_name='Отобразить в разделе наши работы НЕТ/ДА')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ширина (см)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Высота (см)')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Глубина (см)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='admin_service.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ['-created_at'],
            },
        ),
    ]
