# Generated by Django 5.2.6 on 2025-09-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
