# Generated by Django 6.0.2 on 2026-02-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='friday_close',
            field=models.TimeField(blank=True, help_text='Формат: ЧЧ:ММ', null=True, verbose_name='Пятница - Закрытие'),
        ),
        migrations.AddField(
            model_name='contact',
            name='friday_open',
            field=models.TimeField(blank=True, help_text='Формат: ЧЧ:ММ', null=True, verbose_name='Пятница - Открытие'),
        ),
        migrations.AddField(
            model_name='contact',
            name='monday_close',
            field=models.TimeField(blank=True, help_text='Формат: ЧЧ:ММ', null=True, verbose_name='Понедельник - Закрытие'),
        ),
        migrations.AddField(
            model_name='contact',
            name='monday_open',
            field=models.TimeField(blank=True, help_text='Формат: ЧЧ:ММ', null=True, verbose_name='Понедельник - Открытие'),
        ),
        migrations.AddField(
            model_name='contact',
            name='saturday_close',
            field=models.TimeField(blank=True, help_text='Формат: ЧЧ:ММ', null=True, verbose_name='Суббота - Закрытие'),
        ),
        migrations.AddField(
            model_name='contact',
            name='saturday_open',
            field=models.TimeField(blank=True, help_text='Формат: ЧЧ:ММ', null=True, verbose_name='Суббота - Открытие'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sunday_close',
            field=models.TimeField(blank=True, help_text='Формат: ЧЧ:ММ', null=True, verbose_name='Воскресенье - Закрытие'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sunday_open',
            field=models.TimeField(blank=True, help_text='Формат: ЧЧ:ММ', null=True, verbose_name='Воскресенье - Открытие'),
        ),
        migrations.AddField(
            model_name='contact',
            name='thursday_close',
            field=models.TimeField(blank=True, help_text='Формат: ЧЧ:ММ', null=True, verbose_name='Четверг - Закрытие'),
        ),
        migrations.AddField(
            model_name='contact',
            name='thursday_open',
            field=models.TimeField(blank=True, help_text='Формат: ЧЧ:ММ', null=True, verbose_name='Четверг - Открытие'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tuesday_close',
            field=models.TimeField(blank=True, help_text='Формат: ЧЧ:ММ', null=True, verbose_name='Вторник - Закрытие'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tuesday_open',
            field=models.TimeField(blank=True, help_text='Формат: ЧЧ:ММ', null=True, verbose_name='Вторник - Открытие'),
        ),
        migrations.AddField(
            model_name='contact',
            name='wednesday_close',
            field=models.TimeField(blank=True, help_text='Формат: ЧЧ:ММ', null=True, verbose_name='Среда - Закрытие'),
        ),
        migrations.AddField(
            model_name='contact',
            name='wednesday_open',
            field=models.TimeField(blank=True, help_text='Формат: ЧЧ:ММ', null=True, verbose_name='Среда - Открытие'),
        ),
    ]
