# Generated by Django 6.0.2 on 2026-02-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0002_contact_friday_close_contact_friday_open_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='friday_close',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='friday_open',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='monday_close',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='monday_open',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='saturday_close',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='saturday_open',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sunday_close',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sunday_open',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='thursday_close',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='thursday_open',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tuesday_close',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tuesday_open',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='wednesday_close',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='wednesday_open',
        ),
    ]
