# Generated by Django 5.2.6 on 2025-09-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0002_work_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-created_at'], 'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AddField(
            model_name='work',
            name='country',
            field=models.CharField(choices=[('us', 'United States'), ('fr', 'France'), ('de', 'Germany')], default='us', max_length=5, verbose_name='Страна работы'),
        ),
        migrations.AddField(
            model_name='work',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD $'), ('eur', 'EUR €')], default='usd', max_length=5, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='work',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Глубина (см)'),
        ),
        migrations.AddField(
            model_name='work',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Высота (см)'),
        ),
        migrations.AddField(
            model_name='work',
            name='material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В производстве'), ('completed', 'Готово'), ('delivered', 'Доставлено')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='work',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ширина (см)'),
        ),
        migrations.AddField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('custom', 'На заказ'), ('template', 'По шаблону'), ('restoration', 'Реставрация'), ('assembly', 'Сборка'), ('design', 'Дизайн-проект')], default='custom', max_length=20, verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата изготовления'),
        ),
        migrations.AlterField(
            model_name='work',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
