# Generated by Django 5.2.6 on 2026-02-17 00:00

import django.db.models.deletion
from django.db import migrations, models


def create_opening_hours(apps, schema_editor):
    Contact = apps.get_model('admin_service', 'Contact')
    OpeningHour = apps.get_model('admin_service', 'OpeningHour')

    rows = []
    for contact in Contact.objects.all():
        existing_days = set(
            OpeningHour.objects.filter(contact=contact).values_list('day', flat=True)
        )
        for day in range(7):
            if day in existing_days:
                continue
            rows.append(OpeningHour(
                contact=contact,
                day=day,
                open_time=contact.start_time,
                close_time=contact.end_time,
                is_closed=False,
            ))
    if rows:
        OpeningHour.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0003_remove_contact_friday_close_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Mo'), (1, 'Tu'), (2, 'We'), (3, 'Th'), (4, 'Fr'), (5, 'Sa'), (6, 'Su')], verbose_name='День недели')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Выходной')),
                ('open_time', models.TimeField(blank=True, help_text='Формат: ЧЧ:ММ', null=True, verbose_name='Открытие')),
                ('close_time', models.TimeField(blank=True, help_text='Формат: ЧЧ:ММ', null=True, verbose_name='Закрытие')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='admin_service.contact')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'График работы',
                'ordering': ('day',),
            },
        ),
        migrations.AddConstraint(
            model_name='openinghour',
            constraint=models.UniqueConstraint(fields=('contact', 'day'), name='unique_opening_hour_per_day'),
        ),
        migrations.RunPython(create_opening_hours, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='contact',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='end_time',
        ),
    ]
