# Generated by Django 5.2.6 on 2025-09-14 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0003_alter_work_options_work_country_work_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
