# Generated by Django 5.2.6 on 2025-09-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0004_alter_contact_options_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.URLField(blank=True, help_text='https://www.instagram.com/Nickname"', null=True, verbose_name='Страница филлиала в Instagram'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp',
            field=models.URLField(blank=True, help_text='wa.me/+phone_number', null=True, verbose_name='Контактный номер в Whastapp'),
        ),
    ]
