# Generated by Django 6.0.2 on 2026-03-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_service", "0005_aboutpagecontent_remove_work_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carouselphoto",
            name="caption",
        ),
        migrations.RemoveField(
            model_name="carouselphoto",
            name="title",
        ),
        migrations.AlterField(
            model_name="aboutpagecontent",
            name="language",
            field=models.CharField(
                choices=[("de", "Deutsch"), ("fr", "Français")],
                max_length=5,
                unique=True,
                verbose_name="Язык страницы",
            ),
        ),
    ]
