# Generated by Django 5.2.6 on 2025-09-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0005_alter_contact_instagram_alter_contact_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Пример: 21:00', null=True, verbose_name='Закрытие филиала'),
        ),
        migrations.AddField(
            model_name='contact',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Пример: 09:00', null=True, verbose_name='Открытие филиала'),
        ),
    ]
