# Generated by Django 5.2.6 on 2025-09-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0006_contact_end_time_contact_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Пример: 24:00', null=True, verbose_name='Закрытие филлиала'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Пример: 9:00', null=True, verbose_name='Открытие филлиала'),
        ),
    ]
