# Generated by Django 6.0.2 on 2026-03-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_service", "0007_delete_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselphoto",
            name="title",
            field=models.CharField(default="N/A", max_length=120, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="openinghour",
            name="day",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "MO"),
                    (1, "DI"),
                    (2, "MI"),
                    (3, "DO"),
                    (4, "FR"),
                    (5, "SA"),
                    (6, "SO"),
                ],
                verbose_name="День недели",
            ),
        ),
    ]
