# Generated by Django 5.2.6 on 2025-09-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0007_alter_contact_end_time_alter_contact_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество довольных клиентов')),
                ('projects_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Колисество выполненных работ')),
                ('years_experience', models.IntegerField(blank=True, default=0, null=True, verbose_name='Опыт работы')),
                ('delivery_weeks', models.IntegerField(blank=True, default=0, null=True, verbose_name='время доставки')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
