# Generated by Django 5.2.6 on 2025-09-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0008_stats_alter_work_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='delivery_weeks',
            field=models.IntegerField(blank=True, default=0, help_text='Указывайте количество недель', null=True, verbose_name='время доставки'),
        ),
    ]
