# Generated by Django 5.2.6 on 2025-09-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0009_alter_stats_delivery_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
