# Generated by Django 6.0.2 on 2026-05-16 23:51

import admin_service.models
import admin_service.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_work_images(apps, schema_editor):
    Work = apps.get_model("admin_service", "Work")
    WorkImage = apps.get_model("admin_service", "WorkImage")

    for work in Work.objects.exclude(image="").filter(image__isnull=False):
        if WorkImage.objects.filter(work_id=work.pk).exists():
            continue

        WorkImage.objects.create(
            work_id=work.pk,
            image=work.image.name,
            order=0,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0009_alter_category_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselphoto',
            name='image',
            field=models.ImageField(upload_to='carousel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), admin_service.validators.validate_image_upload], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), admin_service.validators.validate_image_upload], verbose_name='Фотография мебели'),
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=admin_service.models.work_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), admin_service.validators.validate_image_upload], verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admin_service.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Изображение работы',
                'verbose_name_plural': 'Изображения работы',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['work', 'order'], name='work_image_order_idx')],
            },
        ),
        migrations.RunPython(
            copy_legacy_work_images,
            migrations.RunPython.noop,
        ),
    ]
