# Generated by Django 5.2.6 on 2025-09-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0010_contact_latitude_contact_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('consultation_type', models.CharField(choices=[('design', 'Дизайн-проект'), ('custom', 'На заказ'), ('repair', 'Ремонт/Реставрация'), ('general', 'Общая консультация')], default='general', max_length=20, verbose_name='Тип консультации')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('preferred_time', models.CharField(blank=True, max_length=50, verbose_name='Предпочтительное время')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка на консультацию',
                'verbose_name_plural': 'Заявки на консультацию',
                'ordering': ['-created_at'],
            },
        ),
    ]
