# Generated by Django 5.2.6 on 2025-09-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0011_consultationrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date'], 'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.IntegerField(default=0, verbose_name='Количество полезных голосов'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='Проверенный клиент'),
        ),
        migrations.AddField(
            model_name='review',
            name='project_name',
            field=models.CharField(blank=True, default='Мебель на заказ', max_length=200, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], default=5, verbose_name='Рейтинг'),
        ),
    ]
