# Generated by Django 5.2.6 on 2025-10-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0012_alter_review_options_review_helpful_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, default='Описание проекта бла-бла-бла-бла-бла-бла-бла-бла-бла-бла-', verbose_name='Текст отзыва'),
        ),
    ]
