# Generated by Django 5.2.6 on 2025-10-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0013_alter_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.URLField(blank=True, default='https://www.instagram.com/', help_text='https://www.instagram.com/Nickname"', null=True, verbose_name='Страница филлиала в Instagram'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp',
            field=models.URLField(blank=True, default='wa.me/+', help_text='wa.me/+phone_number', null=True, verbose_name='Контактный номер в Whastapp'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст отзыва'),
        ),
    ]
