# Generated by Django 5.2.6 on 2026-01-19 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0014_alter_contact_instagram_alter_contact_whatsapp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание категории (не обязательно)')),
            ],
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Фотография мебели'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название мебели'),
        ),
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='admin_service.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
