# Generated by Django 5.2.6 on 2026-02-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0015_category_alter_work_image_alter_work_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='longitude',
        ),
    ]
