# Generated by Django 5.2.6 on 2026-02-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0016_remove_contact_latitude_remove_contact_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='has_purchased',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Мебель для продажи ДА/НЕТ'),
        ),
    ]
