# Generated by Django 5.2.6 on 2026-02-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0017_work_has_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='has_purchased',
        ),
        migrations.AddField(
            model_name='work',
            name='for_sale',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='для продажи ДА/НЕТ'),
        ),
    ]
