# Generated by Django 5.2.6 on 2026-02-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0018_remove_work_has_purchased_work_for_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='for_sale',
        ),
        migrations.AddField(
            model_name='work',
            name='our_work',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Отобразить в разделе наши работы НЕТ/ДА'),
        ),
    ]
