# Generated by Django 5.2.6 on 2026-02-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0019_remove_work_for_sale_work_our_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(choices=[('fr', 'Français'), ('at', 'Austria')], default='am', max_length=15, verbose_name='Страна филлиала'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('at', 'Deutsch')], default='en', max_length=5, verbose_name='Основной язык филлиала'),
        ),
        migrations.AlterField(
            model_name='review',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('at', 'Deutsch')], max_length=5, verbose_name='Выбор языка на отзыве'),
        ),
        migrations.AlterField(
            model_name='work',
            name='country',
            field=models.CharField(choices=[('fr', 'France'), ('at', 'Austria')], default='us', max_length=5, verbose_name='Страна работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('at', 'Deutsch')], max_length=5, verbose_name='Выбор языка на работе'),
        ),
    ]
